version: '3.8'

services:
  # Servicio 1: El servidor de MLflow
  mlflow_ui:
    build: .
    container_name: walmart_mlflow_ui
    ports:
      - "5000:5000"
    command: >
      mlflow server  
      --backend-store-uri sqlite:////app/mlflow_data/mlflow.db
      --default-artifact-root /app/mlruns
      --host 0.0.0.0
      --port 5000
    volumes:
      - ./mlruns:/app/mlruns
      - mlflow_data:/app/mlflow_data

  # Servicio 2: Tu script de entrenamiento
  training_job:
    build: .
    container_name: walmart_training_job
    network_mode: "service:mlflow_ui
    command: python run_pipeline.py
    environment:
      # <--- CAMBIO 2: Usar http://mlflow_ui:5000 (nombre del servicio de arriba)
      - MLFLOW_TRACKING_URI=http://mlflow_ui:5000
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./mlruns:/app/mlruns
      - mlflow_data:/app/mlflow_data
    depends_on:
      - mlflow_ui

volumes:
  mlflow_data: