name: MLOps CI Pipeline

# 1. ¿Cuándo se ejecuta esto?
on:
  push:
    branches:[ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # -------------------------------------------------------------
  # JOB 1: Validar código y correr Tests
  # -------------------------------------------------------------
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout del código
      uses: actions/checkout@v4

    - name: 🐍 Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10" # Ajusta si usas 3.9 o 3.11
        cache: 'pip'           # Acelera la instalación cacheando paquetes

    - name: 📦 Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Asegurarnos de tener las herramientas de testing/linting instaladas
        pip install pytest pytest-cov pre-commit

    - name: 🧹 Ejecutar Pre-commit (Linting)
      # Esto leerá tu archivo .pre-commit-config.yaml
      run: pre-commit run --all-files

    - name: 🧪 Ejecutar Tests con Pytest
      # Corre todo lo que esté en la carpeta tests/
      run: pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html

  # -------------------------------------------------------------
  # JOB 2: Probar la construcción de Docker
  # -------------------------------------------------------------
  docker-build-test:
    runs-on: ubuntu-latest
    needs: lint-and-test # Solo se ejecuta si el JOB 1 fue exitoso

    steps:
    - name: 📥 Checkout del código
      uses: actions/checkout@v4

    - name: 🐳 Probar build de Docker
      # Verifica que el Dockerfile compila sin errores
      run: |
        docker build -t demand-forecast-api:test .
